### ISSUE TITLE
切换模型时呼叫API:switch-model发生异常

### ISSUE THREAD

**Issue by tzengshinfu** [josStorer/RWKV-Runner#404]
您好，设定如下：

请求体
```
{
  "customCuda": false,
  "deploy": false,
  "model": "models/RWKV-x060-World-1B6-v2.1-20240328-ctx4096.pth",
  "strategy": "cpu fp32i8",
  "tokenizer": ""
}
```

回传结果
```
{
  "detail": "failed to load: /app/backend-python/rwkv_pip/cpp/librwkv.so: undefined symbol: rwkv_gpu_offload_layers"
}
```

执行方式：docker
docker-compose.yml内容：
```
services:
  rmkv_runner:
    image: rwkv-runner:latest
    build: .
    # Append "--rwkv.cpp" parameter to use rwkv.cpp
    command: python3.10 ./backend-python/main.py  --port 27777 --host 0.0.0.0 --webui --rwkv.cpp
    volumes:
      - /mnt:/mnt
    ports:
      - "27777:27777"
```
